### ISSUE TITLE
Доменные модели часть 2:

### ISSUE THREAD

**Issue by tohak** [tohak/shop#4]
Домеиные модели часть 2
1.счет 
-id
 -id user
 -сумма

2.Акции 
-id
 -% скидки 
-id лист товар

3.История покупок
-id
-дата и время
-ади товара
-ади пользователя
-сумма
4.Новости 
-id
 -новость

5.Реклама
 -id 
-картинка.:

**Comment by MxWild** [comment]
#6 Close
